module.exports = [
    {
        id: 1,
        name: "Apple",
        carbon_footprint: 0.2,
        water_usage: 50,
        land_usage: 0.1,
        packaging: 0.05,
        energy_consumption: 100,
        created_at: new Date("2024-04-01"),
      },
      {
        id: 2,
        name: "Bread",
        carbon_footprint: 1.0,
        water_usage: 200,
        land_usage: 1.5,
        packaging: 0.1,
        energy_consumption: 300,
        created_at: new Date("2024-04-02"),
      },
      {
        id: 3,
        name: "Milk",
        carbon_footprint: 0.5,
        water_usage: 150,
        land_usage: 0.3,
        packaging: 0.2,
        energy_consumption: 200,
        created_at: new Date("2024-04-03"),
      },
    
      // Week 2
      {
        id: 4,
        name: "Lettuce",
        carbon_footprint: 0.8,
        water_usage: 100,
        land_usage: 0.5,
        packaging: 0.1,
        energy_consumption: 150,
        created_at: new Date("2024-04-08"),
      },
      {
        id: 5,
        name: "Chicken",
        carbon_footprint: 2.0,
        water_usage: 300,
        land_usage: 2.0,
        packaging: 0.3,
        energy_consumption: 400,
        created_at: new Date("2024-04-09"),
      },
      {
        id: 6,
        name: "Orange",
        carbon_footprint: 0.3,
        water_usage: 60,
        land_usage: 0.2,
        packaging: 0.05,
        energy_consumption: 120,
        created_at: new Date("2024-04-10"),
      },
    
      // Week 3
      {
        id: 7,
        name: "Rice",
        carbon_footprint: 0.4,
        water_usage: 80,
        land_usage: 0.4,
        packaging: 0.08,
        energy_consumption: 130,
        created_at: new Date("2024-04-15"),
      },
      {
        id: 8,
        name: "Cheese",
        carbon_footprint: 1.2,
        water_usage: 250,
        land_usage: 1.0,
        packaging: 0.15,
        energy_consumption: 280,
        created_at: new Date("2024-04-16"),
      },
      {
        id: 9,
        name: "Spinach",
        carbon_footprint: 0.6,
        water_usage: 120,
        land_usage: 0.6,
        packaging: 0.1,
        energy_consumption: 140,
        created_at: new Date("2024-04-17"),
      },
    
      // Week 4
      {
        id: 10,
        name: "Eggs",
        carbon_footprint: 0.3,
        water_usage: 70,
        land_usage: 0.3,
        packaging: 0.07,
        energy_consumption: 110,
        created_at: new Date("2024-04-22"),
      },
      {
        id: 11,
        name: "Beef",
        carbon_footprint: 6.0,
        water_usage: 600,
        land_usage: 5.0,
        packaging: 0.5,
        energy_consumption: 700,
        created_at: new Date("2024-04-23"),
      },
      {
        id: 12,
        name: "Potatoes",
        carbon_footprint: 0.4,
        water_usage: 90,
        land_usage: 0.4,
        packaging: 0.08,
        energy_consumption: 120,
        created_at: new Date("2024-04-24"),
      },
    ];
